/// Built-in language grammars.
library;

import 'grammar.dart';

/// Dart language grammar.
const LangGrammar dart = LangGrammar(
  name: 'dart',
  keywords: [
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'base',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'Function',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'late',
    'library',
    'mixin',
    'new',
    'null',
    'on',
    'operator',
    'part',
    'required',
    'rethrow',
    'return',
    'sealed',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'typedef',
    'var',
    'void',
    'when',
    'while',
    'with',
    'yield',
  ],
  types: [
    'int',
    'double',
    'num',
    'String',
    'bool',
    'List',
    'Map',
    'Set',
    'Future',
    'Stream',
    'Iterable',
    'Object',
    'dynamic',
    'Never',
    'Type',
    'Symbol',
    'Null',
    'Duration',
    'DateTime',
    'Uri',
    'Record',
    'BigInt',
    'RegExp',
    'Comparable',
    'Pattern',
  ],
  lineComment: '//',
  blockComment: ('/*', '*/'),
  stringDelimiters: ['"', "'"],
  multiLineStringDelimiters: ['"""', "'''"],
  annotationPrefix: '@',
  punctuationChars: '(){}[]<>;:,.?',
  operatorChars: '+-*/%=!&|^~',
  multiCharOperators: [
    '<<=',
    '>>=',
    '>>>',
    '~/=',
    '??=',
    '<<',
    '>>',
    '<=',
    '>=',
    '==',
    '!=',
    '&&',
    '||',
    '??',
    '?.',
    '=>',
    '~/',
    '+=',
    '-=',
    '*=',
    '/=',
    '%=',
    '&=',
    '|=',
    '^=',
  ],
  identifiersAllowDollar: true,
  rawStringPrefix: 'r',
);

/// Scala language grammar.
const LangGrammar scala = LangGrammar(
  name: 'scala',
  keywords: [
    'abstract',
    'as',
    'case',
    'catch',
    'class',
    'def',
    'derives',
    'do',
    'else',
    'end',
    'enum',
    'export',
    'extends',
    'extension',
    'false',
    'final',
    'finally',
    'for',
    'forSome',
    'given',
    'if',
    'implicit',
    'import',
    'inline',
    'infix',
    'lazy',
    'match',
    'new',
    'null',
    'object',
    'opaque',
    'open',
    'override',
    'package',
    'private',
    'protected',
    'return',
    'sealed',
    'super',
    'then',
    'this',
    'throw',
    'trait',
    'transparent',
    'true',
    'try',
    'type',
    'using',
    'val',
    'var',
    'while',
    'with',
    'yield',
  ],
  types: [
    'Int',
    'Long',
    'Short',
    'Byte',
    'Float',
    'Double',
    'Char',
    'Boolean',
    'String',
    'Unit',
    'Nothing',
    'Any',
    'AnyRef',
    'AnyVal',
    'Option',
    'Some',
    'None',
    'Either',
    'Left',
    'Right',
    'List',
    'Map',
    'Set',
    'Seq',
    'Vector',
    'Array',
    'Future',
    'Try',
    'Success',
    'Failure',
  ],
  lineComment: '//',
  blockComment: ('/*', '*/'),
  stringDelimiters: ['"', "'"],
  multiLineStringDelimiters: ['"""'],
  annotationPrefix: '@',
  punctuationChars: '(){}[]<>;:,.?',
  operatorChars: '+-*/%=!&|^~',
  multiCharOperators: [
    '<<=',
    '>>=',
    '>>>',
    '<=',
    '>=',
    '==',
    '!=',
    '&&',
    '||',
    '<<',
    '>>',
    '<-',
    '->',
    '=>',
    '::',
    '+=',
    '-=',
    '*=',
    '/=',
    '%=',
    '&=',
    '|=',
    '^=',
  ],
  identifierStringPrefix: true,
  backtickIdentifiers: true,
);

/// YAML 1.2 grammar (flow-collection keys, quoted strings, anchors,
/// aliases, comments).
///
/// Block scalars (`|`, `>`) tokenize the indented body as regular YAML
/// content rather than as a single string literal.
const LangGrammar yaml = LangGrammar(
  name: 'yaml',
  keywords: ['true', 'false', 'null'],
  lineComment: '#',
  stringDelimiters: ['"', "'"],
  punctuationChars: '[]{},:-',
  operatorChars: '&*!%|>',
);

/// JSON grammar, lenient for highlighting purposes.
///
/// Tokenizes technically-invalid JSON inputs (hex literals, leading
/// zeros) as numbers rather than rejecting them. For strict validation
/// use a JSON parser.
const LangGrammar json = LangGrammar(
  name: 'json',
  keywords: ['true', 'false', 'null'],
  stringDelimiters: ['"'],
  punctuationChars: '{}[]:,',
  operatorChars: '',
);

/// Shell / Bash grammar.
const LangGrammar shell = LangGrammar(
  name: 'shell',
  keywords: [
    'if',
    'then',
    'else',
    'elif',
    'fi',
    'for',
    'while',
    'until',
    'do',
    'done',
    'case',
    'esac',
    'in',
    'function',
    'return',
    'exit',
    'local',
    'export',
    'readonly',
    'declare',
    'typeset',
    'source',
    'eval',
    'exec',
    'set',
    'unset',
    'true',
    'false',
  ],
  lineComment: '#',
  stringDelimiters: ['"', "'"],
  punctuationChars: '(){}[];,',
  operatorChars: r'=!<>&|+-*/%',
  multiCharOperators: [
    '<<=',
    '>>=',
    '==',
    '!=',
    '<=',
    '>=',
    '&&',
    '||',
    '<<',
    '>>',
    '+=',
    '-=',
    '*=',
    '/=',
    '%=',
  ],
  annotationPrefix: null,
  shellVariables: true,
  backtickCommandSubstitution: true,
  heredocs: true,
);

/// Look up a built-in grammar by name.
///
/// Returns `null` if no built-in grammar matches.
LangGrammar? grammarFor(String language) => switch (language) {
  'dart' => dart,
  'scala' => scala,
  'yaml' || 'yml' => yaml,
  'json' => json,
  'sh' || 'bash' || 'shell' || 'zsh' => shell,
  _ => null,
};
